version: "3"

services:
  api:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app

  www:
    build: ./www
    ports:
      - "8000:80"
    volumes:
      - ./www/html:/usr/share/nginx/html

